site_name: ansi2html
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
